### ISSUE TITLE
Add center to print log

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#1]
![image](https://cloud.githubusercontent.com/assets/1191344/25382286/891c92cc-29d4-11e7-937d-374586b5ec29.png)

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25580287/5c0df6e0-2e9d-11e7-90a2-921ab0ad29f9.png)
Completed in UAT.

**Comment by satmist** [comment]
Displaying items 1 - 10 of 25
Pagination is needed in Batch Printing.

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25792674/9e61936a-33e5-11e7-941a-d7b1d7f6f4ea.png)
Ready for UAT.
