### ISSUE TITLE
When center/subcenter is added it will be available in dropdown directly. No need to request ambatech to refresh the pool. Convert inline queries to SP.

### ISSUE THREAD

**Issue by jp96** [dadabhagwan/ICardImprovement#11]
Center Sub-Center queries required to be converted to SP.

**Comment by jp96** [comment]
Completed in UAT.

**Comment by satmist** [comment]
Now rights are with Kavinbhai, Need to talk to Jineshbhai.

**Comment by amba-tech** [comment]
@ashish-shah please contact me and explain the actual issue - Jinesh

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25854136/a622114e-34ec-11e7-8dfa-b0e9137d49a8.png)
Ready for UAT.
