### ISSUE TITLE
Set Default flag to N for DUPLICATE ID CARDS ENTRY.

### ISSUE THREAD

**Issue by satmist** [dadabhagwan/ICardImprovement#14]
![image](https://cloud.githubusercontent.com/assets/28336466/25771401/9d62296c-326d-11e7-8da6-f3f5b82866f9.png)

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25772398/99c710d2-3287-11e7-919e-cd0432febf14.png)
Ready for UAT.

**Comment by amba-tech** [comment]
ok.. - Jinesh
