### ISSUE TITLE
For out of India make only first name duplicate in Gujarati.

### ISSUE THREAD

**Issue by satmist** [dadabhagwan/ICardImprovement#15]

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25791484/4f85455e-33de-11e7-8ea6-b50206eb713c.png)

For Out of India Only.

Existing Logic:
FName == Gujarati FName & LName == Gujarati LName

New Logic:
Only compare FName == Gujarati FName.

**Comment by amba-tech** [comment]
please explain the reason for the proposed change .. - Jinesh

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25887764/076fde1a-3581-11e7-8c56-f0369c3c3441.png)
Ready for UAT.
