### ISSUE TITLE
Replace X mark with dustbin icon

### ISSUE THREAD

**Issue by satmist** [dadabhagwan/ICardImprovement#16]
![image](https://cloud.githubusercontent.com/assets/28336466/25771631/8e2909a0-3274-11e7-9eb6-37b3ac8ee848.png)

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25772368/efcdc4ae-3286-11e7-93fb-24b8c2e6045c.png)
Ready for UAT.
