### ISSUE TITLE
On Person Entry Screen - Center Sub-Center field make compulsory?

### ISSUE THREAD

**Issue by jp96** [dadabhagwan/ICardImprovement#17]

**Comment by amba-tech** [comment]
yes

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25848196/dd60ec9a-34d6-11e7-8361-889da926e587.png)
Ready for UAT.

**Comment by jp96** [comment]
@ashish-shah  Client will require to do end to end testing.
