### ISSUE TITLE
Downloaded Excel should have P_DATE in Date format

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#3]

**Comment by ashish-shah** [comment]
![image](https://cloud.githubusercontent.com/assets/1191344/25382781/b5207f58-29d6-11e7-886a-7d017fca4fa8.png)

**Comment by ashish-shah** [comment]
Ankhil: Date shorting : latest/newsest date first

**Comment by ashish-shah** [comment]
Ankhil : and second short on name ...A to Z

**Comment by ashish-shah** [comment]
Only the filtered data should come in excel

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25619592/161b174a-2f69-11e7-833e-da6cf314d402.png)
Completed in UAT.

**Comment by jp96** [comment]
Filter data download not working.

**Comment by jp96** [comment]
Filter data download is working.
