### ISSUE TITLE
Option to delete icard entry from print and halt screens

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#4]
![image](https://cloud.githubusercontent.com/assets/1191344/25383559/5006dbb8-29da-11e7-9bf5-21ab3638086b.png)

1. Option need to be given to Icard admin to delete an entry from the batch and halt log. This is required in case of double or duplicate entries done by an admin. 
2. It is a soft delete. The deleted icard id should not be reused. It should be mark deleted with reason "Data error"
3.  Deleted entry should not show up in "search" or "report"

**Comment by ashish-shah** [comment]
This feature is not required in Halt screen as we are giving provision to transfer status from H to P and when it is in P you may delete it

**Comment by satmist** [comment]
Completed in UAT .... Pending Testing
