### ISSUE TITLE
Change status of multiple icards from 'H' to 'P'

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#5]
![image](https://cloud.githubusercontent.com/assets/1191344/25470711/17226228-2b41-11e7-935d-6c2bfd323fe6.png)

Facility to change status of multiple icard in halt log from H to P so that those selected can be bulk printed

**Comment by satmist** [comment]
Completed In UAT ... pending internal testing
![image](https://cloud.githubusercontent.com/assets/28336466/25649853/71fa8f36-2ff6-11e7-9a81-2dc544a7543d.png)

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25663341/08569590-3035-11e7-932a-b68233a9b2d3.png)
Remove dropdown dependency from verify and Print button.

**Comment by jp96** [comment]
Question - Selective printing is required or not?

**Comment by ashish-shah** [comment]
User Training : Multiple selection box is ONLY for status change and has no effect on print button. When print button is hit, all the grid rows goes for printing irrespective of checkbox selection
