### ISSUE TITLE
In "search existing address" screen remove address (not add id) and replace it with city details

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#6]
![image](https://cloud.githubusercontent.com/assets/1191344/25470839/b9d81c88-2b41-11e7-870f-be900def5b29.png)

'Address' is not used, so remove it. Don't remove 'Add id'
Add 'city details' so that address based on city is searched

**Comment by ashish-shah** [comment]
Screen should have 1)Add id and 2)City id. Remove 3)Address

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25650459/b5025594-2ffa-11e7-870a-0950a365d26b.png)
Completed in UAT.

**Comment by satmist** [comment]
![image](https://cloud.githubusercontent.com/assets/28336466/25771440/0ee46df6-326f-11e7-93c3-4b5213752636.png)
City Name instead of City Id.

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25793156/8cf47284-33e8-11e7-8932-873834cb36f8.png)
Ready for UAT.
