### ISSUE TITLE
Field additions to Person entry screen

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#8]
![image](https://cloud.githubusercontent.com/assets/1191344/25478783/119ebee0-2b60-11e7-8d44-3ad67cdbb577.png)

1) Display HR id (read only)
2.1) Display Approver by name [what will be displayed in this field for existing icard holders] (not for data entry..during retrieval only)
2.2) Also put filed for Approver ID ( for data entry)
3) Display who last modified this icard
4) Display the date of last modification

**Comment by ashish-shah** [comment]
Ankhil : Display Approver ID in (read only) also

**Comment by ashish-shah** [comment]
First time entry :  HRID : No , Approved by Id:Yes, Approved by name: No, Modified by date: No (sys capture), Modified by : Login name

Retrieval :  HRID : Yes, if it is there , Approved by Id: Yes, Approved by name: Yes, Modified by date: Yes (sys capture), Modified by : Login name

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25579632/24a55b36-2e97-11e7-8278-a4e408f4b17b.png)
Completed in UAT.

**Comment by jp96** [comment]
Approver Id is set at the time on Person Entry creation only. It's will not be updated once set. Confirm with Ankilbhai.

**Comment by ashish-shah** [comment]
Logic for Approver ID:

1) Existing records : before birth of this feature
      Do backend update query with ID of person who is never going to be approver (ex Belaben etc). Ankhil to advice on this
2) New records :  Approver id can only be entered for the first time and after that it is read only. Approver id can be edited till the card has not gone for printing for first time.

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25700432/5fe747ae-30e5-11e7-878b-4830ed434a86.png)
New records : Approver id can only be entered for the first time and after that it is read only. Approver id can be edited till the card has not gone for printing for first time. **Completed**

**Comment by ashish-shah** [comment]
Retrieve Approver Name on entry of ApproverID and lose focus. Should not wait till save

**Comment by jp96** [comment]
Enter ApproverId and press tab to display Approver Name is working.

**Comment by jp96** [comment]
**Query to Update Approver Id.**
Existing records : before birth of this feature
Do backend update query with ID of person who is never going to be approver (ex Belaben etc). Ankhil to advice on this
```
;WITH IDC
    AS (
    SELECT *,
        (SELECT (ISNULL(FNAME,'')+ ' ' + ISNULL(MNAME,'')+ ' ' +ISNULL(LNAME,'')) FROM [dbo].[PERSON_MASTER] WHERE [PERSON_ID] = [APPROVER_ID]) AS APPROVER_NAME,
        (SELECT COUNT(*) FROM [dbo].[IDC_PRINT_DETAILS] WHERE [PERSON_ID] = 126941 AND [STATUS]='y') AS Print_Count
    FROM IDC_PERSON_DETAIL --ORDER BY [CREATED_DATE] DESC
    WHERE CAST([CREATED_DATE] AS date) = '2017/05/03')
    
UPDATE IDC
SET APPROVER_ID = 126941

SELECT *,(
    SELECT (ISNULL(FNAME,'')+ ' ' + ISNULL(MNAME,'')+ ' ' +ISNULL(LNAME,'')) FROM [dbo].[PERSON_MASTER] WHERE [PERSON_ID] = [APPROVER_ID]
    ) AS APPROVER_NAME, [APPROVER_ID],
    (SELECT COUNT(*) FROM [dbo].[IDC_PRINT_DETAILS] WHERE [PERSON_ID] = 126941 AND [STATUS]='y') AS Print_Count
    FROM IDC_PERSON_DETAIL WHERE [CREATED_DATE] < CAST(GETDATE() AS date) ORDER BY [CREATED_DATE] DESC
```

**Comment by satmist** [comment]
Show stopper - Create new record and verify in Batch print screen.

**Comment by jp96** [comment]
Show stopper is fixed.

Below action has to be taken from Icard Team.

Query to Update Approver Id.
Existing records : before birth of this feature
Do backend update query with ID of person who is never going to be approver (ex Belaben etc). Ankhil to advice on this

;WITH IDC
    AS (
    SELECT *,
        (SELECT (ISNULL(FNAME,'')+ ' ' + ISNULL(MNAME,'')+ ' ' +ISNULL(LNAME,'')) FROM [dbo].[PERSON_MASTER] WHERE [PERSON_ID] = [APPROVER_ID]) AS APPROVER_NAME,
        (SELECT COUNT(*) FROM [dbo].[IDC_PRINT_DETAILS] WHERE [PERSON_ID] = 126941 AND [STATUS]='y') AS Print_Count
    FROM IDC_PERSON_DETAIL --ORDER BY [CREATED_DATE] DESC
    WHERE CAST([CREATED_DATE] AS date) = '2017/05/03')
    
UPDATE IDC
SET APPROVER_ID = 126941

SELECT *,(
    SELECT (ISNULL(FNAME,'')+ ' ' + ISNULL(MNAME,'')+ ' ' +ISNULL(LNAME,'')) FROM [dbo].[PERSON_MASTER] WHERE [PERSON_ID] = [APPROVER_ID]
    ) AS APPROVER_NAME, [APPROVER_ID],
    (SELECT COUNT(*) FROM [dbo].[IDC_PRINT_DETAILS] WHERE [PERSON_ID] = 126941 AND [STATUS]='y') AS Print_Count
    FROM IDC_PERSON_DETAIL WHERE [CREATED_DATE] < CAST(GETDATE() AS date) ORDER BY [CREATED_DATE] DESC

**Comment by satmist** [comment]
The show-stopper has been checked and is working.... there was a error in the batch print sql query that prevented the records being shown... has been resolved

**Comment by jp96** [comment]
`;WITH IDC
    AS (
    SELECT [ipd].*,(
    SELECT (ISNULL(FNAME,'')+ ' ' + ISNULL(MNAME,'')+ ' ' +ISNULL(LNAME,'')) FROM [dbo].[PERSON_MASTER] WHERE [PERSON_ID] = [APPROVER_ID]
    ) AS APPROVER_NAME,
    (SELECT COUNT(*) FROM [dbo].[IDC_PRINT_DETAILS] WHERE [PERSON_ID] = 5030 AND [STATUS]='y') AS Print_Count,
        [country].[CountryName], [pml].[MODULE_ID]        
    FROM IDC_PERSON_DETAIL ipd
    INNER JOIN [dbo].[PERSON_MODULE_LINK] pml ON [pml].[PERSON_ID] = ipd.[PERSON_ID]
    INNER JOIN [dbo].[ADDRESS_MASTER] am ON [pml].[ADDRESS_ID] = [am].[ADDRESS_ID]
    INNER JOIN [dbo].[CITY_MASTER] cm ON [cm].[CITY_ID] = [am].[CITY_ID]
    CROSS APPLY (SELECT [CountryName] FROM [dbo].[fnc_lookup_City]([am].[CITY_ID])) AS country   
    --WHERE [APPROVER_ID] IS NULL ORDER BY [ipd].[CREATED_DATE] DESC
    WHERE [ipd].[CREATED_DATE] < '2014/06/01' AND [pml].[MODULE_ID] = 4 AND [country].[CountryName] <> 'india'
    --ORDER BY [ipd].[PERSON_ID]
    )

UPDATE IDC
SET APPROVER_ID = 5030

SELECT *,(
    SELECT (ISNULL(FNAME,'')+ ' ' + ISNULL(MNAME,'')+ ' ' +ISNULL(LNAME,'')) FROM [dbo].[PERSON_MASTER] WHERE [PERSON_ID] = [APPROVER_ID]
    ) AS APPROVER_NAME, [APPROVER_ID],
    (SELECT COUNT(*) FROM [dbo].[IDC_PRINT_DETAILS] WHERE [PERSON_ID] = 5030 AND [STATUS]='y') AS Print_Count,
[country].[CountryName]
    FROM IDC_PERSON_DETAIL ipd
    INNER JOIN [dbo].[PERSON_MODULE_LINK] pml ON [pml].[PERSON_ID] = ipd.[PERSON_ID]
    INNER JOIN [dbo].[ADDRESS_MASTER] am ON [pml].[ADDRESS_ID] = [am].[ADDRESS_ID]
    INNER JOIN [dbo].[CITY_MASTER] cm ON [cm].[CITY_ID] = [am].[CITY_ID]
    CROSS APPLY (SELECT [CountryName] FROM [dbo].[fnc_lookup_City]([am].[CITY_ID])) AS country    
    WHERE [ipd].[CREATED_DATE] < '2014/06/01' AND [pml].[MODULE_ID] IN (4) AND [country].[CountryName] <> 'india'  ORDER BY [ipd].[CREATED_DATE] DESC
    
    
    SELECT * FROM [dbo].[IDC_PERSON_DETAIL] WHERE [APPROVER_ID] IS NULL
 `
