### ISSUE TITLE
Reprint multiple icard

### ISSUE THREAD

**Issue by ashish-shah** [dadabhagwan/ICardImprovement#9]
![image](https://cloud.githubusercontent.com/assets/1191344/25482304/d10004c0-2b6e-11e7-8e72-53f6b72bf5c4.png)

Use case:
100 icards are sent to press for printing
Out of these icards , 1 sheet is not proper, and that needs to be reprinted

Solution:
Go to reprint screen
Enter date on which they are given out for printing
Multi-select the icards that are failed
Queue them for reprint

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25659621/40a3eee8-3026-11e7-9e76-6ad68a7f5a42.png)
Completed in UAT.

**Comment by satmist** [comment]
Reprint records are not reflecting in Batch Printing Screen.

**Comment by jp96** [comment]
![image](https://cloud.githubusercontent.com/assets/3703266/25773168/784e7008-3296-11e7-9bfa-08242b131971.png)
![image](https://cloud.githubusercontent.com/assets/3703266/25773174/8bb03eb0-3296-11e7-8400-91f3ca4614d3.png)
Ready for UAT.
